// The small-size variant of assets/icon.svg: the same drawing without the elements marked
// class="detail" (border, cursor underline), which only add noise at 16-24px.

const DETAIL_ELEMENT = /\s*<[^>]*\bclass="detail"[^>]*\/>/g;
const COMMENT = /\s*<!--[\s\S]*?-->/g;

/** @param {string} svg  contents of assets/icon.svg (detail elements are self-closing) */
function smallIconSvg(svg) {
  const body = svg.replace(COMMENT, '').replace(DETAIL_ELEMENT, '');
  return `<!-- Generated by scripts/build-icon.cjs from assets/icon.svg (npm run build:icon). Do not edit. -->\n${body}`;
}

module.exports = { smallIconSvg };
