import { describe, it, expect } from 'vitest'
import iconSvg from './iconSvg.cjs'

const { smallIconSvg } = iconSvg

describe('smallIconSvg', () => {
  it('drops the elements marked class="detail" and the authoring comment, keeping everything else', () => {
    const source = [
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">',
      '  <!-- notes for whoever edits the icon -->',
      '  <rect x="8" y="8" width="240" height="240" rx="58" fill="#111"/>',
      '  <rect class="detail" x="9" y="9" width="238" height="238" fill="none"/>',
      '  <path d="M50 95 L88 129" stroke="#4ff0a8"/>',
      '  <rect class="detail" x="104" y="183" width="108" height="12"/>',
      '</svg>'
    ].join('\n')

    const small = smallIconSvg(source)

    expect(small).not.toContain('class="detail"')
    expect(small).not.toContain('notes for whoever')
    expect(small).toContain('<rect x="8" y="8" width="240"')
    expect(small).toContain('<path d="M50 95 L88 129"')
    expect(small.startsWith('<!-- Generated by scripts/build-icon.cjs')).toBe(true)
  })
})
